# -- Main Menu --
[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

# -- Footer Menu --
[[footer]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 20
